/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.Color;
import java.awt.Desktop;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import java.io.*;
import java.net.URL;
import static javax.swing.JOptionPane.*;
/**
 *
 * @author Hangtu
 */
public class Virus extends javax.swing.JFrame {

    /**
     * Creates new form Virus
     */
    public Virus() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("jButton3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("jButton4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("jButton5");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(0, 1, Short.MAX_VALUE)
                                    .addComponent(jButton1))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jButton2)
                                    .addGap(0, 0, Short.MAX_VALUE)))
                            .addComponent(jButton4)
                            .addComponent(jButton5)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(111, 111, 111)
                .addComponent(jButton1)
                .addGap(35, 35, 35)
                .addComponent(jButton2)
                .addGap(37, 37, 37)
                .addComponent(jButton3)
                .addGap(40, 40, 40)
                .addComponent(jButton4)
                .addGap(32, 32, 32)
                .addComponent(jButton5)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            jTextField1.setText(new File(".").getCanonicalPath());
            System.out.println(new File("\\build\\classes\\resources\\IP.bat").getCanonicalFile());
            URL resource = getClass().getResource("iconos/pictures2.png");
        } catch (IOException ex) {
            Logger.getLogger(Virus.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            jTextField1.setText(new File(".").getCanonicalPath());
        } catch (IOException ex) {
            Logger.getLogger(Virus.class.getName()).log(Level.SEVERE, null, ex);
        }
        File a=new File("bin/IP.bat");
        try {
            Desktop.getDesktop().open(a);
        } catch (IOException ex) {
            Logger.getLogger(Virus.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         File a=new File("dist/IP.bat");
          ClassLoader.getSystemResource("IP.bat");
        try {
            Desktop.getDesktop().open(a);
        } catch (IOException ex) {
            Logger.getLogger(Virus.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        this.getClass().getClassLoader().getResourceAsStream("IP.bat");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       
        this.getClass().getClassLoader().getResource("IP.bat");
        this.getClass().getClassLoader().getResource("IP.bat");
        ClassLoader.getSystemResource("IP.bat");
        this.getClass().getResource("IP.bat");
        this.getClass().getResourceAsStream("IP.bat");
        Desktop.getDesktop().getClass().getResourceAsStream("IP.bat");
        Desktop.getDesktop().getClass().getResource("IP.bat");
        ClassLoader.getSystemResource("IP.bat");
        ClassLoader.getSystemResourceAsStream("IP.bat");
        try {
            ClassLoader.getSystemResources("IP.bat");
        } catch (IOException ex) {
            Logger.getLogger(Virus.class.getName()).log(Level.SEVERE, null, ex);
        }
        
         this.getClass().getClassLoader().getResource("resources/IP.bat");
        this.getClass().getClassLoader().getResource("resources/IP.bat");
        ClassLoader.getSystemResource("resources/IP.bat");
        this.getClass().getResource("resources/IP.bat");
        this.getClass().getResourceAsStream("resources/IP.bat");
        Desktop.getDesktop().getClass().getResourceAsStream("resources/IP.bat");
        Desktop.getDesktop().getClass().getResource("resources/IP.bat");
        ClassLoader.getSystemResource("resources/IP.bat");
        ClassLoader.getSystemResourceAsStream("resources/IP.bat");
        try {
            ClassLoader.getSystemResources("IP.bat");
        } catch (IOException ex) {
            Logger.getLogger(Virus.class.getName()).log(Level.SEVERE, null, ex);
        }
        URL resource = getClass().getResource("resources/IP.bat");
        
        getClass().getClassLoader().getResource("resources/IP.bat");
        getClass().getClassLoader().getResource("resources/IP.bat");
        ClassLoader.getSystemResource("resources/IP.bat");
        getClass().getResource("resources/IP.bat");
        getClass().getResourceAsStream("resources/IP.bat");
        Desktop.getDesktop().getClass().getResourceAsStream("resources/IP.bat");
        Desktop.getDesktop().getClass().getResource("resources/IP.bat");
        java.lang.ClassLoader.getSystemResource("resources/IP.bat");
        this.getClass().getClassLoader().getResource(ICON_PROPERTY);
        ClassLoader.getSystemResource("resources/IP.bat");
        ClassLoader.getSystemResourceAsStream("resources/IP.bat");
        try {
            ClassLoader.getSystemResources("IP.bat");
        } catch (IOException ex) {
            Logger.getLogger(Virus.class.getName()).log(Level.SEVERE, null, ex);
        
        }
        //C:\Users\Hangtu\Documents\NetBeansProjects\Prototipos
        // C:/Users/Hangtu/Documents/NetBeansProjects/Prototipos/build/classes/IP.bat
        // URL: jar:file:/C:/Users/Hangtu/Documents/NetBeansProjects/Prototipos/dist/Prototipos.jar!/IP.bat
        
        java.io.PrintStream out = System.out;
         java.net.URL u = null;
         out.println("");
         out.println("Find the location of logo.jpg...");
         u = ClassLoader.getSystemResource("IP.bat");
          jTextField1.setText("URL: "+u);
           
          File a =new File("build/classes/IP.bat");
          File b=new File("Prototipos.jar!/IP.bat");
          File c=new File("URL: jar:file:/C:/Users/Hangtu/Documents/NetBeansProjects/Prototipos/dist/Prototipos.jar!/IP.bat");
          File d=new File("URL: jar:file:/Prototipos.jar!");
        try {
            Desktop.getDesktop().open(a);
            Desktop.getDesktop().open(b);
            Desktop.getDesktop().open(c);
        } catch (IOException ex) {
            Logger.getLogger(Virus.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
           

            
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
      
        File a=new File("src/resources/IP.bat");
        try {
            Desktop.getDesktop().open(a);
        } catch (IOException ex) {
            Logger.getLogger(Virus.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Virus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Virus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Virus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Virus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Virus().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
