
import java.awt.Color;
import java.lang.*;
import javax.swing.table.*;


import java.sql.DriverManager;
	import java.sql.Connection;
	import java.lang.ClassNotFoundException;
	import java.sql.SQLException;
	import java.sql.*;
	import java.awt.Dialog;
	import javax.swing.JOptionPane;
        import java.awt.Desktop.*;
        import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FramePrincipal.java
 *
 * Created on 16/11/2013, 11:57:50 AM
 */
/**
 *
 * @author fabricas
 */
public class FramePrincipal extends javax.swing.JFrame implements java.lang.Runnable{
    String status[] = new String[9];
   
    /** Creates new form FramePrincipal */
    
    Thread hilo;
    public FramePrincipal() {
        initComponents();
        hilo=new Thread(this);
        hilo.start();
        panel1.setBackground(Color.white);
       // MostrarDatos();
       // MostrarDisponible();

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jPopupMenu3 = new javax.swing.JPopupMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jPopupMenu4 = new javax.swing.JPopupMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jPopupMenu5 = new javax.swing.JPopupMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jPopupMenu6 = new javax.swing.JPopupMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jPopupMenu7 = new javax.swing.JPopupMenu();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jPopupMenu8 = new javax.swing.JPopupMenu();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jPopupMenu9 = new javax.swing.JPopupMenu();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenuItem19 = new javax.swing.JMenuItem();
        panel1 = new java.awt.Panel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jButton10 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();

        jMenuItem1.setText("Libre");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem1);

        jMenuItem2.setText("Ocupado");
        jMenuItem2.setComponentPopupMenu(jPopupMenu1);
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem2);

        jMenuItem3.setText("Libre");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jPopupMenu2.add(jMenuItem3);

        jMenuItem4.setText("Ocupado");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jPopupMenu2.add(jMenuItem4);

        jMenuItem5.setText("Libre");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jPopupMenu3.add(jMenuItem5);

        jMenuItem6.setText("Ocupado");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jPopupMenu3.add(jMenuItem6);

        jMenuItem7.setText("Libre");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jPopupMenu4.add(jMenuItem7);

        jMenuItem8.setText("Ocupado");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jPopupMenu4.add(jMenuItem8);

        jMenuItem9.setText("Libre");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jPopupMenu5.add(jMenuItem9);

        jMenuItem10.setText("Ocupado");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jPopupMenu5.add(jMenuItem10);

        jMenuItem11.setText("Libre");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jPopupMenu6.add(jMenuItem11);

        jMenuItem12.setText("Ocupado");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jPopupMenu6.add(jMenuItem12);

        jMenuItem13.setText("Libre");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jPopupMenu7.add(jMenuItem13);

        jMenuItem14.setText("Ocupado");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jPopupMenu7.add(jMenuItem14);

        jMenuItem15.setText("Libre");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        jPopupMenu8.add(jMenuItem15);

        jMenuItem16.setText("Ocupado");
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16ActionPerformed(evt);
            }
        });
        jPopupMenu8.add(jMenuItem16);

        jMenuItem17.setText("Libre");
        jMenuItem17.setToolTipText("");
        jMenuItem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem17ActionPerformed(evt);
            }
        });
        jPopupMenu9.add(jMenuItem17);

        jMenuItem18.setText("Ocupado");
        jMenuItem18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem18ActionPerformed(evt);
            }
        });
        jPopupMenu9.add(jMenuItem18);

        jMenuItem19.setText("jMenuItem19");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Waiter Online - Software");
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(-1,true));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        panel1.setName("Tabla 2"); // NOI18N

        jTabbedPane1.setToolTipText("");

        jPanel1.setBackground(new java.awt.Color(-1,true));

        jButton1.setBackground(new java.awt.Color(-1,true));
        jButton1.setFont(new java.awt.Font("Dialog", 0, 24));
        jButton1.setText("1");
        jButton1.setComponentPopupMenu(jPopupMenu2);

        jButton2.setBackground(new java.awt.Color(-1,true));
        jButton2.setFont(new java.awt.Font("Dialog", 0, 24));
        jButton2.setText("2");
        jButton2.setComponentPopupMenu(jPopupMenu1);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(-1,true));
        jButton3.setFont(new java.awt.Font("Dialog", 0, 24));
        jButton3.setText("3");
        jButton3.setComponentPopupMenu(jPopupMenu3);

        jButton4.setBackground(new java.awt.Color(-1,true));
        jButton4.setFont(new java.awt.Font("Dialog", 0, 24));
        jButton4.setText("4");
        jButton4.setComponentPopupMenu(jPopupMenu4);

        jButton5.setBackground(new java.awt.Color(-1,true));
        jButton5.setFont(new java.awt.Font("Dialog", 0, 24));
        jButton5.setText("5");
        jButton5.setComponentPopupMenu(jPopupMenu5);

        jButton6.setBackground(new java.awt.Color(-1,true));
        jButton6.setFont(new java.awt.Font("Dialog", 0, 24));
        jButton6.setText("6");
        jButton6.setComponentPopupMenu(jPopupMenu6);

        jButton7.setBackground(new java.awt.Color(-1,true));
        jButton7.setFont(new java.awt.Font("Dialog", 0, 24));
        jButton7.setText("7");
        jButton7.setComponentPopupMenu(jPopupMenu7);

        jButton8.setBackground(new java.awt.Color(-1,true));
        jButton8.setFont(new java.awt.Font("Dialog", 0, 24));
        jButton8.setText("8");
        jButton8.setComponentPopupMenu(jPopupMenu8);

        jButton9.setBackground(new java.awt.Color(-1,true));
        jButton9.setFont(new java.awt.Font("Dialog", 0, 24));
        jButton9.setText("9");
        jButton9.setComponentPopupMenu(jPopupMenu9);

        jButton10.setText("Actualizar");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 698, Short.MAX_VALUE)
                    .addComponent(jButton10, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton7)
                        .addGap(18, 18, 18)
                        .addComponent(jButton8)
                        .addGap(18, 18, 18)
                        .addComponent(jButton9))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addGap(18, 18, 18)
                        .addComponent(jButton5)
                        .addGap(18, 18, 18)
                        .addComponent(jButton6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)))
                .addContainerGap(373, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(jButton6))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7)
                    .addComponent(jButton8)
                    .addComponent(jButton9))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton10)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Control - Reservados", jPanel1);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton11.setFont(new java.awt.Font("Dialog", 1, 14));
        jButton11.setText("Actualizar");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setFont(new java.awt.Font("Dialog", 1, 14));
        jButton12.setText("Borrar");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.setFont(new java.awt.Font("Dialog", 1, 14));
        jButton13.setText("Generar Cuenta");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton12, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                    .addComponent(jButton13, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                    .addComponent(jButton11, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton12)
                        .addGap(11, 11, 11)
                        .addComponent(jButton13)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Pedidos", jPanel2);

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(291, 291, 291)
                        .addComponent(jLabel1))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jTabbedPane1)))
                .addContainerGap())
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(176, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 22, Short.MAX_VALUE)
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 22, Short.MAX_VALUE)
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panel1.getAccessibleContext().setAccessibleName("Control - Pedido");

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
    
    try {
        for(int i=0; i<9;i++){
	Class.forName("com.mysql.jdbc.Driver");
        Connection conexion = DriverManager.getConnection("jdbc:mysql://10.54.0.163:3306/snack_online", "qooke", "");
        Statement st=conexion.createStatement();
        st.executeUpdate("UPDATE `mesa` SET `disponible`='"+status[i]+"'WHERE idMesa='"+(i+1)+"'");
    }
                MostrarDisponible();
}
         catch(ClassNotFoundException f){f.printStackTrace();} 
catch(SQLException f){f.printStackTrace(); }

}//GEN-LAST:event_jButton10ActionPerformed

private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
    jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabricas\\Pictures\\ICONOS\\ok-icon (1).png"));
    status[1]="s";
}//GEN-LAST:event_jMenuItem1ActionPerformed

private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
    jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabricas\\Pictures\\ICONOS\\Actions-application-exit-icon.png"));
    status[1]="n";
}//GEN-LAST:event_jMenuItem2ActionPerformed

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jButton2ActionPerformed

private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabricas\\Pictures\\ICONOS\\ok-icon (1).png"));status[0]="s";
}//GEN-LAST:event_jMenuItem3ActionPerformed

private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabricas\\Pictures\\ICONOS\\Actions-application-exit-icon.png"));status[0]="n";
}//GEN-LAST:event_jMenuItem4ActionPerformed

private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
jButton3.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabricas\\Pictures\\ICONOS\\ok-icon (1).png"));status[2]="s";
}//GEN-LAST:event_jMenuItem5ActionPerformed

private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
jButton3.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabricas\\Pictures\\ICONOS\\Actions-application-exit-icon.png"));status[2]="n";
}//GEN-LAST:event_jMenuItem6ActionPerformed

private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
jButton4.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabricas\\Pictures\\ICONOS\\ok-icon (1).png"));status[3]="s";
}//GEN-LAST:event_jMenuItem7ActionPerformed

private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
jButton4.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabricas\\Pictures\\ICONOS\\Actions-application-exit-icon.png"));status[3]="n";
}//GEN-LAST:event_jMenuItem8ActionPerformed

private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
jButton5.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabricas\\Pictures\\ICONOS\\ok-icon (1).png"));status[4]="s";
}//GEN-LAST:event_jMenuItem9ActionPerformed

private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
jButton5.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabricas\\Pictures\\ICONOS\\Actions-application-exit-icon.png"));status[4]="n";
}//GEN-LAST:event_jMenuItem10ActionPerformed

private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
jButton6.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabricas\\Pictures\\ICONOS\\ok-icon (1).png"));status[5]="s";
}//GEN-LAST:event_jMenuItem11ActionPerformed

private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
jButton6.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabricas\\Pictures\\ICONOS\\Actions-application-exit-icon.png"));status[5]="n";
}//GEN-LAST:event_jMenuItem12ActionPerformed

private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
jButton7.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabricas\\Pictures\\ICONOS\\ok-icon (1).png"));status[6]="s";
}//GEN-LAST:event_jMenuItem13ActionPerformed

private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
jButton7.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabricas\\Pictures\\ICONOS\\Actions-application-exit-icon.png"));status[6]="n";
}//GEN-LAST:event_jMenuItem14ActionPerformed

private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
jButton8.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabricas\\Pictures\\ICONOS\\ok-icon (1).png"));status[7]="s";
}//GEN-LAST:event_jMenuItem15ActionPerformed

private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed
jButton8.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabricas\\Pictures\\ICONOS\\Actions-application-exit-icon.png"));status[7]="n";
}//GEN-LAST:event_jMenuItem16ActionPerformed

private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem17ActionPerformed
jButton9.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabricas\\Pictures\\ICONOS\\ok-icon (1).png"));status[8]="s";
}//GEN-LAST:event_jMenuItem17ActionPerformed

private void jMenuItem18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem18ActionPerformed
jButton9.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabricas\\Pictures\\ICONOS\\Actions-application-exit-icon.png"));status[8]="n";
}//GEN-LAST:event_jMenuItem18ActionPerformed

private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
MostrarDatos();
}//GEN-LAST:event_jButton11ActionPerformed

private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
 int fila=jTable1.getSelectedRow();
if(fila >=0){
    try {
	Class.forName("com.mysql.jdbc.Driver");
        Connection conexion = DriverManager.getConnection("jdbc:mysql://10.54.0.163:3306/snack_online", "qooke", "");
        Statement st=conexion.createStatement();
        int id;
        id=Integer.parseInt(jTable1.getValueAt(fila, 0).toString());
        int opc=JOptionPane.showOptionDialog(null,"En verdad desea eliminar esta pizza?","CONFIRMACION",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE,null,null,null);
        if(opc==0){
            st.executeUpdate("DELETE FROM pedido WHERE idPedido='"+id+"'");
            JOptionPane.showMessageDialog(null,"ELIMINACION EXITOSA","EXITO",JOptionPane.INFORMATION_MESSAGE);
            MostrarDatos();
}
     }
         catch(ClassNotFoundException f){f.printStackTrace();} 
catch(SQLException f){f.printStackTrace(); }
}
else{JOptionPane.showMessageDialog(null,"No se ha seleccionado ninguna Fila","ERROR AL SELECCIONAR LA FILA",JOptionPane.ERROR_MESSAGE);
}
}//GEN-LAST:event_jButton12ActionPerformed

private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
    new FrameCuenta().setVisible(true);
}//GEN-LAST:event_jButton13ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public void MostrarDisponible(){
        
        String con="";
        con="SELECT disponible FROM mesa";
        String []datos = new String [9];
        try {
	Class.forName("com.mysql.jdbc.Driver");
        Connection conexion = DriverManager.getConnection("jdbc:mysql://10.54.0.163:3306/snack_online", "qooke", "");
        Statement st=conexion.createStatement();
        ResultSet rs=st.executeQuery(con);
        int i=0;
        while(rs.next()){
            datos[i]=rs.getString("disponible");
            status[i]=rs.getString("disponible");
            i++;
        }
        if(datos[0].equals("s")){jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabricas\\Pictures\\ICONOS\\ok-icon (1).png"));
        }else{jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabricas\\Pictures\\ICONOS\\Actions-application-exit-icon.png")); }
        if(datos[1].equals("s")){jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabricas\\Pictures\\ICONOS\\ok-icon (1).png"));
        }else{jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabricas\\Pictures\\ICONOS\\Actions-application-exit-icon.png")); }
        if(datos[2].equals("s")){jButton3.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabricas\\Pictures\\ICONOS\\ok-icon (1).png"));
        }else{jButton3.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabricas\\Pictures\\ICONOS\\Actions-application-exit-icon.png")); }
        if(datos[3].equals("s")){jButton4.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabricas\\Pictures\\ICONOS\\ok-icon (1).png"));
        }else{jButton4.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabricas\\Pictures\\ICONOS\\Actions-application-exit-icon.png")); }
        if(datos[4].equals("s")){jButton5.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabricas\\Pictures\\ICONOS\\ok-icon (1).png"));
        }else{jButton5.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabricas\\Pictures\\ICONOS\\Actions-application-exit-icon.png")); }
        if(datos[5].equals("s")){jButton6.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabricas\\Pictures\\ICONOS\\ok-icon (1).png"));
        }else{jButton6.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabricas\\Pictures\\ICONOS\\Actions-application-exit-icon.png")); }
        if(datos[6].equals("s")){jButton7.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabricas\\Pictures\\ICONOS\\ok-icon (1).png"));
        }else{jButton7.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabricas\\Pictures\\ICONOS\\Actions-application-exit-icon.png")); }
        if(datos[7].equals("s")){jButton8.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabricas\\Pictures\\ICONOS\\ok-icon (1).png"));
        }else{jButton8.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabricas\\Pictures\\ICONOS\\Actions-application-exit-icon.png")); }
        if(datos[8].equals("s")){jButton9.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabricas\\Pictures\\ICONOS\\ok-icon (1).png"));
        }else{jButton9.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabricas\\Pictures\\ICONOS\\Actions-application-exit-icon.png")); }
                 }
         catch(ClassNotFoundException f){f.printStackTrace();} 
catch(SQLException f){f.printStackTrace(); } 
    
    }
    
    public void MostrarDatos(){
        DefaultTableModel modelo= new DefaultTableModel();
        modelo.addColumn("PEDIDO");
        modelo.addColumn("MESA");
        modelo.addColumn("PLATILLO");
        modelo.addColumn("CANTIDAD");
        jTable1.setModel(modelo);
        String con="";
        con="SELECT (P.IDPEDIDO)as idPedido ,(M.IDMESA)AS MESA, (MEN.NOMBRE)as platillo, (p.cantidad)as cantidad FROM PEDIDO P, MENU MEN , MESA M WHERE FK_IDMESA=IDMESA AND FK_IDMENU=IDMENU"  ;
        String []datos = new String [4];
        try {
	Class.forName("com.mysql.jdbc.Driver");
        Connection conexion = DriverManager.getConnection("jdbc:mysql://10.54.0.163:3306/snack_online", "qooke", "");
        Statement st=conexion.createStatement();
        ResultSet rs=st.executeQuery(con);
        while(rs.next()){
            datos[0]=rs.getString("idPedido");
            datos[1]=rs.getString("Mesa");
            datos[2]=rs.getString("Platillo");
            datos[3]=rs.getString("Cantidad");
            modelo.addRow(datos);
            
        }
        jTable1.setModel(modelo);
                 }
         catch(ClassNotFoundException f){f.printStackTrace();} 
catch(SQLException f){f.printStackTrace(); } 
      
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {              
                new FramePrincipal().setVisible(true); 
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JPopupMenu jPopupMenu3;
    private javax.swing.JPopupMenu jPopupMenu4;
    private javax.swing.JPopupMenu jPopupMenu5;
    private javax.swing.JPopupMenu jPopupMenu6;
    private javax.swing.JPopupMenu jPopupMenu7;
    private javax.swing.JPopupMenu jPopupMenu8;
    private javax.swing.JPopupMenu jPopupMenu9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private java.awt.Panel panel1;
    // End of variables declaration//GEN-END:variables
  
     public void dato(){
        
        System.out.print("Hola");
        
    }
    @Override
    public void run() {
        while(true){
            try {
                Thread.sleep(3000);
                MostrarDatos();
            } catch (InterruptedException ex) {
                Logger.getLogger(FramePrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
}
