
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.Random;
import javax.swing.ImageIcon;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Hangtu
 */
public class Juego extends javax.swing.JFrame {

    /**
     * Creates new form Juego
     */
    private Imagenes imagen;
    private Random aleatorio=new Random();
    private ArrayList <Imagenes> list=new ArrayList<>();
    private int puntos=0;
  
    
    private Imagenes a=new Imagenes("apple",new ImageIcon(getClass().getResource("/imagenes/apple.jpg")));
    private Imagenes b=new Imagenes("avocado",new ImageIcon(getClass().getResource("/imagenes/avocado.jpg")));
    private Imagenes c=new Imagenes("banana",new ImageIcon(getClass().getResource("/imagenes/banana.jpg")));
    private Imagenes d=new Imagenes("blackberry",new ImageIcon(getClass().getResource("/imagenes/blackberry.jpg")));
    private Imagenes e=new Imagenes("blueberry",new ImageIcon(getClass().getResource("/imagenes/blueberry.jpg")));
    private Imagenes f=new Imagenes("cherry",new ImageIcon(getClass().getResource("/imagenes/cherry.jpg")));
    private Imagenes g=new Imagenes("coconut",new ImageIcon(getClass().getResource("/imagenes/coconut.jpg")));
    private Imagenes h=new Imagenes("grapes",new ImageIcon(getClass().getResource("/imagenes/grapes.jpg")));
    private Imagenes i=new Imagenes("lemon",new ImageIcon(getClass().getResource("/imagenes/lemon.jpg")));
    private Imagenes j=new Imagenes("lime",new ImageIcon(getClass().getResource("/imagenes/lime.jpg")));
    private Imagenes k=new Imagenes("mango",new ImageIcon(getClass().getResource("/imagenes/mango.jpg")));
    private Imagenes l=new Imagenes("melon",new ImageIcon(getClass().getResource("/imagenes/melon.jpg")));
    private Imagenes m=new Imagenes("pear",new ImageIcon(getClass().getResource("/imagenes/pear.jpg")));
    private Imagenes n=new Imagenes("strawberry",new ImageIcon(getClass().getResource("/imagenes/strawberry.jpg")));
    private Imagenes o=new Imagenes("watermelon",new ImageIcon(getClass().getResource("/imagenes/watermelon.jpg")));
   
    
    public Juego() {
        initComponents();
        objetosLista();
        this.setLocationRelativeTo(null);
        name.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label = new javax.swing.JLabel();
        btnStart = new javax.swing.JButton();
        name = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Write The Fruit Name");
        setResizable(false);

        label.setBackground(new java.awt.Color(255, 255, 255));
        label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fruit.jpg"))); // NOI18N

        btnStart.setText("Start");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });

        name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nameKeyPressed(evt);
            }
        });

        jLabel1.setText("FIND THE NAME");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(btnStart, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel1)))
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnStart))
                .addGap(43, 43, 43))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        
        escoger();
        btnStart.setEnabled(false);
        name.setEnabled(true);
    }//GEN-LAST:event_btnStartActionPerformed

    private void nameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameKeyPressed
        if(evt.getKeyCode()== KeyEvent.VK_ENTER){
           if(name.getText().equalsIgnoreCase(imagen.getNombre())){
           
           javax.swing.JOptionPane.showMessageDialog(this,"GOOD :D");
           name.setText("");
           escoger();
           puntos++;
       }
       else{
            javax.swing.JOptionPane.showMessageDialog(this,"I'M SORRY - YOUR SCORE: "+puntos);
            label.setIcon(null);
            name.setText("");
            name.setEnabled(false);
            btnStart.setEnabled(true);
            puntos=0;
       }
       }
    }//GEN-LAST:event_nameKeyPressed
   
    private void objetosLista(){
        list.add(a);
        list.add(b);
        list.add(c);
        list.add(d);
        list.add(e);
        list.add(f);
        list.add(g);
        list.add(h);
        list.add(i);
        list.add(j);
        list.add(k);
        list.add(l);
        list.add(m);
        list.add(n);
        list.add(o);
       
    }
    
    private void escoger(){
        imagen=list.get(aleatorio.nextInt(list.size()));
        label.setIcon(imagen.getImagen());
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Juego().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnStart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel label;
    private javax.swing.JTextField name;
    // End of variables declaration//GEN-END:variables
}
