package pojos;
// Generated 10-feb-2014 19:25:57 by Hibernate Tools 3.2.1.GA



/**
 * HijosId generated by hbm2java
 */
public class HijosId  implements java.io.Serializable {


     private int idHijos;
     private int padresIdPadres;

    public HijosId() {
    }

    public HijosId(int idHijos, int padresIdPadres) {
       this.idHijos = idHijos;
       this.padresIdPadres = padresIdPadres;
    }
   
    public int getIdHijos() {
        return this.idHijos;
    }
    
    public void setIdHijos(int idHijos) {
        this.idHijos = idHijos;
    }
    public int getPadresIdPadres() {
        return this.padresIdPadres;
    }
    
    public void setPadresIdPadres(int padresIdPadres) {
        this.padresIdPadres = padresIdPadres;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof HijosId) ) return false;
		 HijosId castOther = ( HijosId ) other; 
         
		 return (this.getIdHijos()==castOther.getIdHijos())
 && (this.getPadresIdPadres()==castOther.getPadresIdPadres());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdHijos();
         result = 37 * result + this.getPadresIdPadres();
         return result;
   }   


}


