package pojos;
// Generated 10-feb-2014 19:25:57 by Hibernate Tools 3.2.1.GA



/**
 * Hijos generated by hbm2java
 */
public class Hijos  implements java.io.Serializable {


     private HijosId id;
     private Padres padres;
     private String nombre;
     private String edad;
     private String numero;
     private byte[] foto;

    public Hijos() {
    }

	
    public Hijos(HijosId id, Padres padres, String nombre) {
        this.id = id;
        this.padres = padres;
        this.nombre = nombre;
    }
    public Hijos(HijosId id, Padres padres, String nombre, String edad, String numero, byte[] foto) {
       this.id = id;
       this.padres = padres;
       this.nombre = nombre;
       this.edad = edad;
       this.numero = numero;
       this.foto = foto;
    }
   
    public HijosId getId() {
        return this.id;
    }
    
    public void setId(HijosId id) {
        this.id = id;
    }
    public Padres getPadres() {
        return this.padres;
    }
    
    public void setPadres(Padres padres) {
        this.padres = padres;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getEdad() {
        return this.edad;
    }
    
    public void setEdad(String edad) {
        this.edad = edad;
    }
    public String getNumero() {
        return this.numero;
    }
    
    public void setNumero(String numero) {
        this.numero = numero;
    }
    public byte[] getFoto() {
        return this.foto;
    }
    
    public void setFoto(byte[] foto) {
        this.foto = foto;
    }




}


