package pojos;
// Generated 10-feb-2014 19:25:57 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Padres generated by hbm2java
 */
public class Padres  implements java.io.Serializable {


     private Integer idPadres;
     private String nombre;
     private Integer edad;
     private String telefono;
     private Date fecha;
     private Set hijoses = new HashSet(0);

    public Padres() {
    }

	
    public Padres(String nombre) {
        this.nombre = nombre;
    }
    public Padres(String nombre, Integer edad, String telefono, Date fecha, Set hijoses) {
       this.nombre = nombre;
       this.edad = edad;
       this.telefono = telefono;
       this.fecha = fecha;
       this.hijoses = hijoses;
    }
   
    public Integer getIdPadres() {
        return this.idPadres;
    }
    
    public void setIdPadres(Integer idPadres) {
        this.idPadres = idPadres;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Integer getEdad() {
        return this.edad;
    }
    
    public void setEdad(Integer edad) {
        this.edad = edad;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Set getHijoses() {
        return this.hijoses;
    }
    
    public void setHijoses(Set hijoses) {
        this.hijoses = hijoses;
    }




}


