package Frames;



import Clases_Simulador.File_05_Data;
import Clases_Terminal.File_02_Comandos;
import java.awt.Image;
import java.awt.Toolkit;

import java.awt.event.KeyEvent;

/**
 *
 * @author Hangtu
 */
public class Terminal extends javax.swing.JFrame {
    
    private File_02_Comandos lineaC;
    private Simulador simulador;
    private File_05_Data datos;
    
    /**
     * Creates new form Terminal
     */
    
    public Terminal() {
        initComponents();
        this.setLocation(0,0);
        simulador=new Simulador(); 
        this.datos=simulador.getDatos();
        lineaC=new File_02_Comandos(terminal,this,datos,simulador);
        terminal.setText(lineaC.nuevo());
        terminal.setCaretPosition(30);
        datos.limpiarMarcos();
        datos.getIDMarcosVacios();
    }
    
     public  Image getIconImage(){
    Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/favicon5.png"));
    return retValue;
     } 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        terminal = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sismo v3.0");
        setIconImage(getIconImage());
        setResizable(false);

        terminal.setColumns(20);
        terminal.setRows(5);
        terminal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                terminalKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(terminal);

        jLabel2.setText("Click Para Ver Simulacion De Los Procesos");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 715, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(265, 265, 265)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void terminalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_terminalKeyReleased
         if(evt.getKeyCode()==KeyEvent.VK_ENTER){  
          try{
           lineaC.leerLinea();
           lineaC.dividirLinea();
           lineaC.determinarComando();
           lineaC.renovar();
          }
          catch(Exception ex){
           System.out.println("Error En Clase Principal");
           lineaC.renovar();
          }
        }
    }//GEN-LAST:event_terminalKeyReleased

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        simulador.setVisible(true);
    }//GEN-LAST:event_jLabel2MouseClicked
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea terminal;
    // End of variables declaration//GEN-END:variables
}