/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package calculadoravoz;

import Voz.ReconocimientoVoz;
import javax.swing.JOptionPane;

/**
 *
 * @author Carlos
 */
public class Calculadora extends javax.swing.JFrame implements Runnable {

    private double operando1;
    private double operando2;
    private double resultado;
    
    /**Permite saber si se ejecuto una accion matematica*/
    private boolean presionadoAccion;
    
    /**Permite saber cuan es la accion(Operacion) matematica que se ejecuto*/
    private byte accion;
    public ReconocimientoVoz escuchar;
    public Thread hiloEscucha;

    public Calculadora() {
        initComponents();
        this.setLocationRelativeTo(this);
        this.setVisible(true);
        this.presionadoAccion = false;
        this.txtNumero.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNumero = new javax.swing.JFormattedTextField();
        btnResta = new javax.swing.JButton();
        btnMultiplicacion = new javax.swing.JButton();
        btnSuma = new javax.swing.JButton();
        btnDivision = new javax.swing.JButton();
        btnResultado = new javax.swing.JButton();
        btnBorrarTodo = new javax.swing.JButton();
        btnBorrarTodo1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtNumero.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        txtNumero.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtNumero.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N

        btnResta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnResta.setText("-");
        btnResta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestaActionPerformed(evt);
            }
        });

        btnMultiplicacion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnMultiplicacion.setText("X");
        btnMultiplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiplicacionActionPerformed(evt);
            }
        });

        btnSuma.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSuma.setText("+");
        btnSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumaActionPerformed(evt);
            }
        });

        btnDivision.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnDivision.setText("/");
        btnDivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivisionActionPerformed(evt);
            }
        });

        btnResultado.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnResultado.setText("=");
        btnResultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResultadoActionPerformed(evt);
            }
        });

        btnBorrarTodo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnBorrarTodo.setText("C");
        btnBorrarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarTodoActionPerformed(evt);
            }
        });

        btnBorrarTodo1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnBorrarTodo1.setForeground(new java.awt.Color(255, 0, 0));
        btnBorrarTodo1.setText("Rec");
        btnBorrarTodo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarTodo1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDivision, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBorrarTodo1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnMultiplicacion)
                            .addComponent(btnResta, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBorrarTodo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnResultado)
                        .addGap(3, 3, 3)
                        .addComponent(btnSuma)))
                .addGap(44, 44, 44))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtNumero)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnMultiplicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDivision, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSuma, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnResta, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBorrarTodo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBorrarTodo1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumaActionPerformed
        this.undirBoton((byte) 1);
    }//GEN-LAST:event_btnSumaActionPerformed

    private void btnResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResultadoActionPerformed
        this.undirIgual();
    }//GEN-LAST:event_btnResultadoActionPerformed

    public void undirIgual() {
        this.operando2 = Double.parseDouble(this.txtNumero.getText());
        this.mostrarResultado();
    }

    private void btnRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestaActionPerformed
        this.undirBoton((byte) 2);
    }//GEN-LAST:event_btnRestaActionPerformed

    private void btnDivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivisionActionPerformed
        this.undirBoton((byte) 4);
    }//GEN-LAST:event_btnDivisionActionPerformed

    private void btnMultiplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiplicacionActionPerformed
        this.undirBoton((byte) 3);
    }//GEN-LAST:event_btnMultiplicacionActionPerformed

    private void btnBorrarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarTodoActionPerformed
        this.borrarTodo();
    }//GEN-LAST:event_btnBorrarTodoActionPerformed

    private void btnBorrarTodo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarTodo1ActionPerformed
        this.iniciarReconocimieto();
        JOptionPane.showMessageDialog(rootPane, "Reconocimiento de voz iniciado"
                + "\ncorrectamente....!!", "Comando", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnBorrarTodo1ActionPerformed

    public void borrarTodo() {
        this.txtNumero.setText("");
    }

    private void iniciarReconocimieto() {
        hiloEscucha = new Thread(escuchar = new ReconocimientoVoz(this));
        hiloEscucha.start();
    }

    public void undirBoton(byte accion) {
        this.operando1 = Double.parseDouble(this.txtNumero.getText());
        this.txtNumero.setText("");
        this.accion = accion;
    }

    public void mostrarResultado() {
        switch (this.accion) {
            case 1:
                this.resultado = this.operando1 + this.operando2;
                break;
            case 2:
                this.resultado = this.operando1 - this.operando2;
                break;
            case 3:
                this.resultado = this.operando1 * this.operando2;
                break;
            case 4:
                this.resultado = this.operando1 / this.operando2;
                break;
        }
        this.presionadoAccion = false;
        this.txtNumero.setText(Double.toString(this.resultado));
    }
     public void escribirEnPantalla(String numero) {
        this.txtNumero.setText(this.txtNumero.getText() + numero);
    }

    /**
     * Escribe en la pantalla un numero(0 a 9), que es representado como un
     * caracter de tipo string
     *
     * @param numero string que representa un numero del 0 a 9, se debe tener
     * cuidado este parametro es un string y no se puede operar solo se mostrara
     * en la pantalla de la calculadora
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrarTodo;
    private javax.swing.JButton btnBorrarTodo1;
    private javax.swing.JButton btnDivision;
    private javax.swing.JButton btnMultiplicacion;
    private javax.swing.JButton btnResta;
    private javax.swing.JButton btnResultado;
    private javax.swing.JButton btnSuma;
    private javax.swing.JFormattedTextField txtNumero;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        throw new UnsupportedOperationException("Not supported yet.");
    }
}
